### ISSUE TITLE
It wont let me move anything

### ISSUE THREAD

**Issue by DeanAndMason1314** [NachoEngine/GorillaTag-Player-IK-Blender-Rig#7]
![image_2024-08-28_164631982](https://github.com/user-attachments/assets/01559934-7738-4317-9edc-5635ca7faa6c)
it just dosnt let me move anything

**Comment by BlueGuy242** [comment]
me too bro but try downloading a different one it may help

**Comment by BlueGuy242** [comment]
or maybe ur using Gorilla_IK_Rig if so then use the new version

**Comment by BlueGuy242** [comment]
![Screenshot 2024-09-06 165951](https://github.com/user-attachments/assets/9bba9ea3-e5a1-406c-a17d-5f842a9873f1)
![Screenshot 2024-09-06 170011](https://github.com/user-attachments/assets/72f61a78-c182-4ea5-90ed-d3912f3a4d40)

**Comment by BlueGuy242** [comment]
![Screenshot 2024-09-06 170011](https://github.com/user-attachments/assets/81d040d1-8713-4af3-90dc-d8fb3fd285f5)

**Comment by MusictrollerVR** [comment]
select this its pretty easy

https://github.com/user-attachments/assets/e9acf1e4-9f5b-45bb-91b2-6d9d14b68fe9
